service:
  name: aws-serverless-typescript-template

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10

functions:
  hello:
    handler: src/handler/handler.hello
    events:
      - http:
          method: get
          path: hello
